### ISSUE TITLE
Config bug

### ISSUE THREAD

**Issue by waternoob1005** [OpenFarLands/TheStoneProxy#12]
`2024/06/19 18:51:31 Config error: There is a config, but Network.LocalAddress is empty. Please specify the address where proxy should listen.`

`[Network]
LocalAddress = '0.0.0.0:19132'
RemoteAddress = 'waternoob1005.aternos.me:48335'
Timeout = 20
MotdGetInterval = 1

[OfflineMotd]
Motd = '§c§lOffline'
ProtocolVersion = 1
VersionName = '1.0.0'
LevelName = 'dfsdfs'

[Api]
UseApiServer = false

[Metrics]
UsePrometheus = false`

**Comment by waternoob1005** [comment]
sorry. It was my misunderstanding. We apologize for any harm caused.

**Comment by mikhaillav** [comment]
So no bug here? I can close the issue?
