### ISSUE TITLE
what??

### ISSUE THREAD

**Issue by waternoob1005** [OpenFarLands/TheStoneProxy#14]
![image](https://github.com/OpenFarLands/TheStoneProxy/assets/137138524/cb5f51e8-7cd6-4649-9032-8a6819d925dd)

why?

**Comment by waternoob1005** [comment]
Strangely, this error only occurred on new computers and never occurred on mine
It seems like you need a developer only program to make it work

**Comment by waternoob1005** [comment]
This error also commonly occurs on ordinary people's computers

**Comment by waternoob1005** [comment]
omg thats my miustake so sorry

**Comment by waternoob1005** [comment]
please close this issue so sorry

**Comment by waternoob1005** [comment]
oh no thats not my mistake

**Comment by mikhaillav** [comment]
command `CheckNetIsolation LoopbackExempt -a -n="Microsoft.MinecraftUWP_8wekyb3d8bbwe"` helped 

some explanations [here](https://doc.pmmp.io/en/rtfd/faq/connecting/win10localhostcantconnect.html)
