### ISSUE TITLE
It cannot run

### ISSUE THREAD

**Issue by lutongme** [OpenFarLands/TheStoneProxy#9]
I'm very grateful for the author's program. Before this, I searched for many, but they didn't run very well. I need a lightweight proxy that can display MOTD.

However, it currently cannot work on my computer.
These are some error messages:

OS name:          Microsoft Windows 10 Professional Edition
OS version:          10.0.19044 Build 19044
server version : 1.20.62
game version : 1.20.62 And 1.20.71

----The first time I run it, I can see the MOTD. However, when I join the server, it crashes and exits.--------
TheStoneProxy.exe
2024/03/18 19:12:20 Starting listening on 192.168.58.190:19132, proxying to 119.188.***.143:32321.
panic: runtime error: index out of range [6] with length 1

goroutine 9 [running]:
github.com/OpenFarLands/TheStoneProxy/src/server.(*Server).StartHandle.func1()
        D:/a/TheStoneProxy/TheStoneProxy/src/server/server.go:171 +0x4b9
created by github.com/OpenFarLands/TheStoneProxy/src/server.(*Server).StartHandle in goroutine 34
        D:/a/TheStoneProxy/TheStoneProxy/src/server/server.go:161 +0x1fb

----When joining the server, I restarted it. At that time, Minecraft Bedrock was loading the interface-----
PS E:\pxy> .\TheStoneProxy.exe
2024/03/18 19:12:43 Starting listening on 192.168.58.190:19132, proxying to 119.188.***.143:32321.
2024/03/18 19:12:43 Сlient connected: 192.168.58.250:44626
panic: runtime error: index out of range [6] with length 1

goroutine 20 [running]:
github.com/OpenFarLands/TheStoneProxy/src/server.(*Server).StartHandle.func1()
        D:/a/TheStoneProxy/TheStoneProxy/src/server/server.go:171 +0x4b9
created by github.com/OpenFarLands/TheStoneProxy/src/server.(*Server).StartHandle in goroutine 7
        D:/a/TheStoneProxy/TheStoneProxy/src/server/server.go:161 +0x1fb
----------When returning to the server list page on my phone and starting TheStoneProxy.exe again, it crashes and exits once more.-----
PS E:\pxy> .\TheStoneProxy.exe
2024/03/18 19:12:51 Starting listening on 192.168.58.190:19132, proxying to 119.188.***.143:32321.
panic: runtime error: index out of range [6] with length 1

goroutine 9 [running]:
github.com/OpenFarLands/TheStoneProxy/src/server.(*Server).StartHandle.func1()
        D:/a/TheStoneProxy/TheStoneProxy/src/server/server.go:171 +0x4b9
created by github.com/OpenFarLands/TheStoneProxy/src/server.(*Server).StartHandle in goroutine 34
        D:/a/TheStoneProxy/TheStoneProxy/src/server/server.go:161 +0x1fb

**Comment by mikhaillav** [comment]
Thank you, for this detailed issue! Are you sure you are running the latest version? https://github.com/OpenFarLands/TheStoneProxy/releases/tag/v2.0.2

**Comment by mikhaillav** [comment]
Oh, I see that server motd has only one field so proxy can't parse it (panic: runtime error: index out of range [6] with length 1). See https://wiki.bedrock.dev/servers/raknet-and-mcpe.html#unconnected-pongs

**Comment by mikhaillav** [comment]
Oh, I see that server motd has only one field so proxy can't parse it. See https://wiki.bedrock.dev/servers/raknet-and-mcpe.html#unconnected-pongs

**Comment by mikhaillav** [comment]
Can you please write me in discord or telegram (links in my profile)? I need the server IP to really help you
